import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';

const RobotoFont = Roboto({
  variable: '--font-Roboto',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
  icons: "https://example.com/apple-icon.png"
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang='en'
      className={`${RobotoFont.variable} h-full antialiased`}
    >
      <body className='min-h-full flex flex-col '>{children}</body>
    </html>
  );
}
