import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import Navbar from './Navbar';
import Hero from './Hero';

const roboto = Roboto({ subsets: ['latin'], variable: '--font-roboto' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${roboto.variable} h-full antialiased`}>
      <body className='min-h-full flex flex-col'>
        <Navbar />
        <Hero />
        {children}
      </body>
    </html>
  );
}
