import type { Metadata } from 'next';
import { Roboto, Geist } from 'next/font/google';
import './globals.css';
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const RobotoFont = Roboto({
  variable: '--font-Roboto',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
  icons: "https://example.com/apple-icon.png"
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang='en'
      className={cn("h-full", "antialiased", RobotoFont.variable, "font-sans", geist.variable)}
    >
      <body className='min-h-full flex flex-col '>{children}</body>
    </html>
  );
}
